export enum ContentActions {
  ADD_VACANCY = 'ADD_VACANCY',
  REMOVE_VACANCY = 'REMOVE_VACANCY',
  UPDATE_VACANCY = 'UPDATE_VACANCY',
  ADD_POST = 'ADD_POST',
  REMOVE_POST = 'REMOVE_POST',
  UPDATE_POST = 'UPDATE_POST',
}
